### ISSUE TITLE
Verbose output refers to Characteristics by numeric values even if >9

### ISSUE THREAD

**Issue by Drofseh** [pgorman/travellercharactergenerator#3]
In light of the contributions by @ffilz I decided to try out the verbose mode.

I've noticed that when a characteristic output is >9 during a term or during mustering out it uses a numeral instead of a letter.

Note that it only does this for the verbose output. The UPP at the top displays the correct letter.

Here is an example with corrections marked:
```
Term 4 age 34
Promotion roll 3 + 0 vs 6
Learned Gambling-1
Survival roll 8 + 0 vs 5
Aging strength throw 8 vs 8
Decreased strength by -1 to 4
Aging dexterity throw 4 vs 7
Decreased dexterity by -1 to 11  <--should be B
Aging endurance throw 2 vs 8
Decreased endurance by -1 to 10  <--should be A
Reenlistment roll 10 vs 7
Chose not to reenlist after fourth term.
--------------------------------------------
Mustered Out
10000 credits
10000 credits
5000 credits
Rifle
Improved Rifle-2
Increased intelligence by 1 to 10  <--should be A
```

**Comment by pgorman** [comment]
Yes, the verbose output should probably use hexadecimal for ability scores rather than decimal. I'll fix this, if @ffilz doesn't beat me to it.

**Comment by Drofseh** [comment]
Yah. It's not a big problem but it's nice if things are consistent.

**Comment by ffilz** [comment]
I'll fix it. I have other things cooking.

A friend found a couple other bugs with the latest and I have fixes.

doPromotion is not called for promotions...

I goofed and first term only grants 1 skill...

**Comment by ffilz** [comment]
Oh, there's also an off by 1 bug with aging rolls, they should be < not <=... Got a fix for that.

Will submit a pull request shortly...

**Comment by ffilz** [comment]
BTW, I'm happy to have code reviews on my pull requests, and then re-submit if things need fixing

**Comment by ffilz** [comment]
Submitting a pull request that includes this fix (and actually changes from hex to extended hex, just in case someone actually gets an attribute above 15...).

**Comment by ffilz** [comment]
I added some generation strategy options. The "hunt" option is a GM tool to roll until a certain condition is met. It provides a great way to get a PC with a ship. The "muster" and "maxcash" options give players some control over how mustering out rolls are taken.

**Comment by Drofseh** [comment]
> I added some generation strategy options.

I actually thought about forking this and allowing more choice for the person doing the generating (allowing them do decide when to must out, which branch they want to try to enlist in, etc.) to make it more like actual character creation but my javascript is very weak.

As it is though, I think it's a fantastic tool for GMs to generate NPCs.

**Comment by ffilz** [comment]
Step by step choice would be cool. There is a Java generator here: http://blog.jochenlinnemann.de/?page_id=82 that does allow choices. I haven't looked at it too closely.

This generator has been used by a number of folks for play by post. Sadly there are players who either don't have Classic Traveller, or don't want to spend the time rolling dice. And some want more than a totally random character. Some have been hitting refresh until they get a character with a ship.

My intent to adding some generation strategy is to make it a bit easier for those folks to get what they want. Being able to control how mustering out is done will mean that not all the characters with ships are 7 term scouts or merchants (which was what I was seeing - in part because with the original code, a scout had no chance of a ship without at least 4 terms). The hunt option makes this quick...

And in fact, what I will be doing is running the various options for them (if you're going to use an automated chargen, the GM can run it and supply you with some choices - then we don't have people hitting refresh a hundred times looking for the perfect character). The hunt option takes the first character that meets the requirements...

**Comment by Drofseh** [comment]
I hadn't seen that one before. Thanks!

I definitely like the features you're adding as well.

**Comment by pgorman** [comment]
Thanks!

**Comment by ffilz** [comment]
BTW, I just submitted a new pull request.

I also have a page that documents the options (and links to the chargen as posted on my web page, which will be more or less my latest). I'll try and update if you get ahead of me somehow...

http://www.mindspring.com/~ffilz/Gaming/travellercharacter.html
